import { index, integer, jsonb, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { adminUsersTable } from "./admin_users";

/**
 * Pending preview generated by the AI Admin Copilot
 * (010-ai-admin-copilot, data-model.md §1.1).
 *
 * Lifecycle (per data-model.md §4):
 *   created → first-confirmed → (high-risk: awaiting double) → consumed
 *   created → cancelled (no consumption)
 *   created → expired (TTL elapsed before confirmation)
 *
 * Single-use enforcement: the executor selects the row `FOR UPDATE` with
 * `consumed_at IS NULL AND expires_at > now()` and stamps `consumed_at` in
 * the same transaction as the actual write. Replays land on a row whose
 * predicate no longer matches and are rejected.
 */
export const copilotPreviewsTable = pgTable(
  "copilot_previews",
  {
    /**
     * ULID, generated app-side. Stable, URL-safe, sortable by creation time.
     */
    id: varchar("id", { length: 32 }).primaryKey(),
    /**
     * Owning admin. RESTRICT on delete so wiping an admin with pending
     * previews fails loudly rather than silently orphaning audit context.
     */
    adminId: integer("admin_id")
      .notNull()
      .references(() => adminUsersTable.id, { onDelete: "restrict" }),
    /**
     * Verbatim natural-language input from the admin. Not redacted —
     * admin's own words, recorded so audit can show what was asked.
     */
    intentText: text("intent_text").notNull(),
    /** Tool the LLM called to produce this draft (e.g. `draft_price_change`). */
    toolName: varchar("tool_name", { length: 100 }).notNull(),
    /**
     * Coarse classification used for filtering, risk routing, and metric
     * labels. Vocabulary: `read`, `catalog_edit`, `price_change`,
     * `cost_change`, `stock_change`, `status_change`, `permission_change`,
     * `bulk_*`, `wallet_action`, `phase_flag_change`.
     */
    actionClass: varchar("action_class", { length: 50 }).notNull(),
    /**
     * Risk routing tier. `low` → single confirm. `high` → double confirm
     * with 3-second cooldown. `no_execute` → wallet/refund handoff only.
     */
    riskTier: varchar("risk_tier", { length: 20 }).notNull(),
    /** Array of integer entity IDs the action targets. */
    affectedIds: jsonb("affected_ids").$type<number[]>().notNull(),
    /** Entity type (e.g. `product`, `inventory`, `admin_user`). */
    affectedEntityType: varchar("affected_entity_type", { length: 50 }).notNull(),
    /**
     * Map of `{ id: updated_at_iso }` captured at draft time. The executor
     * re-reads each entity at execute time and aborts if any updated_at has
     * advanced (FR-PREVIEW-004 staleness check).
     */
    recordVersions: jsonb("record_versions").$type<Record<string, string>>().notNull(),
    /**
     * Structured before/after, validation warnings, side-effect notes,
     * sample + aggregate impact for bulk. Discriminated union keyed on
     * `payload.kind` (`"single" | "bulk"`). Shape per data-model.md §2.1.
     */
    previewPayload: jsonb("preview_payload").notNull(),
    /** Concrete model used (e.g. `claude-sonnet-4-6`). For audit. */
    modelId: varchar("model_id", { length: 64 }).notNull(),
    /** Joined to logs/metrics for end-to-end tracing. */
    correlationId: varchar("correlation_id", { length: 64 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    /**
     * Hard TTL — `created_at + 5 minutes` (FR-PREVIEW-003). After this
     * point the executor refuses regardless of staleness.
     */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** Set when the preview is used to execute. NULL means available. */
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    /** First confirmation timestamp (low-risk done after this). */
    confirmedOnceAt: timestamp("confirmed_once_at", { withTimezone: true }),
    /**
     * Set when the second-confirm dialog renders for high-risk previews.
     * Server enforces `confirmed_twice_at >= cooldown_starts_at + 3s`
     * (FR-CONFIRM-002).
     */
    cooldownStartsAt: timestamp("cooldown_starts_at", { withTimezone: true }),
    /** Second-confirmation timestamp. Required for high-risk execute. */
    confirmedTwiceAt: timestamp("confirmed_twice_at", { withTimezone: true }),
  },
  (t) => ({
    // AUD103-1-F3 (r103): DESC mirrors the boot definition (migrate.ts)
    adminCreatedIdx: index("idx_copilot_previews_admin_created").on(
      t.adminId,
      t.createdAt.desc(),
    ),
    expiresIdx: index("idx_copilot_previews_expires").on(t.expiresAt),
    actionClassIdx: index("idx_copilot_previews_action_class").on(t.actionClass),
  }),
);
