import {
  boolean,
  index,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const productsTable = pgTable(
  "products",
  {
    id: serial("id").primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    /**
     * URL-safe slug derived from `name` (or operator-overridden via the
     * admin UI). Used for SEO product URLs (`/product/<slug>`) and the
     * sitemap. Generated by {@link slugifyWithId} on insert/update.
     *
     * Nullable in the schema so the migration can ADD COLUMN before
     * the backfill runs — the runtime invariant is "slug is always
     * present after the post-migration backfill". The unique index
     * `idx_products_slug_unique` enforces collision prevention.
     */
    slug: varchar("slug", { length: 160 }),
    description: text("description"),
    imageUrl: varchar("image_url", { length: 1000 }),
    price: numeric("price", { precision: 10, scale: 2 }).notNull(),
    /**
     * Operator's procurement cost (per unit) — used by the admin pricing
     * calculator to compute margin. Never returned on user-facing /api/products.
     * Nullable because existing rows pre-Increment-1 have no value; new
     * products SHOULD set it but the backend never enforces it.
     */
    costPrice: numeric("cost_price", { precision: 10, scale: 2 }),
    category: varchar("category", { length: 100 }),
    isActive: boolean("is_active").notNull().default(true),
    isArchived: boolean("is_archived").notNull().default(false),
    usageTerms: text("usage_terms"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => ({
    categoryIdx: index("idx_products_category").on(t.category),
    activeIdx: index("idx_products_active").on(t.isActive),
    archivedIdx: index("idx_products_archived").on(t.isArchived),
    activeCategoryIdx: index("idx_products_active_category").on(t.isActive, t.category),
  }),
);

export const insertProductSchema = createInsertSchema(productsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertProduct = z.infer<typeof insertProductSchema>;
export type Product = typeof productsTable.$inferSelect;
